/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppFile1Volumes
 */
export interface AppFile1Volumes {
    /**
     * Container path.
     * @type {string}
     * @memberof AppFile1Volumes
     */
    container?: string;
    /**
     * Host path.
     * @type {string}
     * @memberof AppFile1Volumes
     */
    host?: string;
    /**
     * Description.
     * @type {string}
     * @memberof AppFile1Volumes
     */
    desc?: string;
    /**
     * Type.
     * @type {number}
     * @memberof AppFile1Volumes
     */
    type?: number;
}
