/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppFile2TipsBeforeInstall
 */
export interface AppFile2TipsBeforeInstall {
    /**
     * Content of the tip
     * @type {string}
     * @memberof AppFile2TipsBeforeInstall
     */
    content: string;
    /**
     * Value of the tip
     * @type {string}
     * @memberof AppFile2TipsBeforeInstall
     */
    value?: string;
}
