/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppFile2TipsBeforeInstall } from './app-file2-tips-before-install';
/**
 * Tips of the app
 * @export
 * @interface AppFile2Tips
 */
export interface AppFile2Tips {
    /**
     * Tips before install of the app
     * @type {Array<AppFile2TipsBeforeInstall>}
     * @memberof AppFile2Tips
     */
    beforeInstall?: Array<AppFile2TipsBeforeInstall>;
}
