/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppFile1Ports
 */
export interface AppFile1Ports {
    /**
     * Container.
     * @type {number}
     * @memberof AppFile1Ports
     */
    container?: number;
    /**
     * Host.
     * @type {number}
     * @memberof AppFile1Ports
     */
    host?: number;
    /**
     * Protocol.
     * @type {string}
     * @memberof AppFile1Ports
     */
    protocol?: AppFile1PortsProtocolEnum;
    /**
     * Description.
     * @type {string}
     * @memberof AppFile1Ports
     */
    desc?: string;
    /**
     * Type.
     * @type {number}
     * @memberof AppFile1Ports
     */
    type?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum AppFile1PortsProtocolEnum {
    Tcp = 'tcp',
    Udp = 'udp'
}

