/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Abilities of the app
 * @export
 * @interface AppFile2Abilities
 */
export interface AppFile2Abilities {
    /**
     * 
     * @type {boolean}
     * @memberof AppFile2Abilities
     */
    notification?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppFile2Abilities
     */
    widgets?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppFile2Abilities
     */
    authentification?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppFile2Abilities
     */
    search?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppFile2Abilities
     */
    upnp?: boolean;
}
