/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppFile2Abilities } from './app-file2-abilities';
import { AppFile2Adaptor } from './app-file2-adaptor';
import { AppFile2Changelog } from './app-file2-changelog';
import { AppFile2Container } from './app-file2-container';
import { AppFile2Developer } from './app-file2-developer';
import { AppFile2Tips } from './app-file2-tips';
/**
 * 
 * @export
 * @interface AppFile2
 */
export interface AppFile2 {
    /**
     * Used to identify the version of CasaOS AppFile to do compatibility adaptations
     * @type {string}
     * @memberof AppFile2
     */
    version?: string;
    /**
     * The display name of the app.
     * @type {string}
     * @memberof AppFile2
     */
    title?: string;
    /**
     * For system and container manager naming
     * @type {string}
     * @memberof AppFile2
     */
    name?: string;
    /**
     * The icon of the app.
     * @type {string}
     * @memberof AppFile2
     */
    icon?: string;
    /**
     * A one-sentence description of the App features or value
     * @type {string}
     * @memberof AppFile2
     */
    tagline?: string;
    /**
     * A longer description of the App features or value
     * @type {string}
     * @memberof AppFile2
     */
    overview?: string;
    /**
     * Thumbnail url for Featured Apps list
     * @type {string}
     * @memberof AppFile2
     */
    thumbnail?: string;
    /**
     * A list of screenshots url of the App
     * @type {Array<string>}
     * @memberof AppFile2
     */
    screenshots?: Array<string>;
    /**
     * Category url of this App, can contain multiple categories
     * @type {Array<string>}
     * @memberof AppFile2
     */
    category?: Array<string>;
    /**
     * 
     * @type {AppFile2Developer}
     * @memberof AppFile2
     */
    developer?: AppFile2Developer;
    /**
     * 
     * @type {AppFile2Adaptor}
     * @memberof AppFile2
     */
    adaptor?: AppFile2Adaptor;
    /**
     * 
     * @type {AppFile2Container}
     * @memberof AppFile2
     */
    container?: AppFile2Container;
    /**
     * 
     * @type {AppFile2Abilities}
     * @memberof AppFile2
     */
    abilities?: AppFile2Abilities;
    /**
     * 
     * @type {AppFile2Tips}
     * @memberof AppFile2
     */
    tips?: AppFile2Tips;
    /**
     * 
     * @type {AppFile2Changelog}
     * @memberof AppFile2
     */
    changelog?: AppFile2Changelog;
    /**
     * Latest update date of the app
     * @type {string}
     * @memberof AppFile2
     */
    latestUpdateDate?: string;
}
