/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Web UI of the container
 * @export
 * @interface AppFile2ContainerWebUi
 */
export interface AppFile2ContainerWebUi {
    /**
     * HTTP port of the container
     * @type {string}
     * @memberof AppFile2ContainerWebUi
     */
    http?: string;
    /**
     * HTTPS port of the container
     * @type {string}
     * @memberof AppFile2ContainerWebUi
     */
    https?: string;
    /**
     * Path of the container
     * @type {string}
     * @memberof AppFile2ContainerWebUi
     */
    path?: string;
}
