/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Constraints of the container
 * @export
 * @interface AppFile2ContainerConstraints
 */
export interface AppFile2ContainerConstraints {
    /**
     * Minimum memory needed to run the container (MB)
     * @type {number}
     * @memberof AppFile2ContainerConstraints
     */
    minMemory?: number;
    /**
     * Minimum storage needed to run the container (MB)
     * @type {number}
     * @memberof AppFile2ContainerConstraints
     */
    minStorage?: number;
}
