/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppFile2ContainerPorts
 */
export interface AppFile2ContainerPorts {
    /**
     * Container port of the container
     * @type {string}
     * @memberof AppFile2ContainerPorts
     */
    container?: string;
    /**
     * Host port of the container
     * @type {string}
     * @memberof AppFile2ContainerPorts
     */
    host?: string;
    /**
     * Type of the port
     * @type {string}
     * @memberof AppFile2ContainerPorts
     */
    type?: AppFile2ContainerPortsTypeEnum;
    /**
     * Allocation of the port - required: Only use this port, otherwise do not continue the install - optional: If this host port is available, map it. if not available, do not map it. Both can continue to install - preferred: If this host port is available, map it. if not available it is automatically assigned by the CasaOS. Then continue with the install. - automatic: The host port is automatically assigned by the CasaOS. 
     * @type {string}
     * @memberof AppFile2ContainerPorts
     */
    allocation?: AppFile2ContainerPortsAllocationEnum;
    /**
     * Configurable of the port - no: Not configurable - basic: Configurable in basic mode - advanced: Configurable in advanced mode 
     * @type {string}
     * @memberof AppFile2ContainerPorts
     */
    configurable?: AppFile2ContainerPortsConfigurableEnum;
    /**
     * Description of the port
     * @type {string}
     * @memberof AppFile2ContainerPorts
     */
    description?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum AppFile2ContainerPortsTypeEnum {
    Tcp = 'tcp',
    Udp = 'udp'
}
/**
    * @export
    * @enum {string}
    */
export enum AppFile2ContainerPortsAllocationEnum {
    Required = 'required',
    Optional = 'optional',
    Preferred = 'preferred',
    Automatic = 'automatic'
}
/**
    * @export
    * @enum {string}
    */
export enum AppFile2ContainerPortsConfigurableEnum {
    False = 'false',
    Basic = 'basic',
    Advanced = 'advanced'
}

