/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppFile2ContainerEnvs
 */
export interface AppFile2ContainerEnvs {
    /**
     * Name of the env
     * @type {string}
     * @memberof AppFile2ContainerEnvs
     */
    key?: string;
    /**
     * Value of the env
     * @type {string}
     * @memberof AppFile2ContainerEnvs
     */
    value?: string;
    /**
     * Configurable of the env - no: Not configurable - basic: Configurable in basic mode - advanced: Configurable in advanced mode 
     * @type {string}
     * @memberof AppFile2ContainerEnvs
     */
    configurable?: AppFile2ContainerEnvsConfigurableEnum;
    /**
     * Description of the env
     * @type {string}
     * @memberof AppFile2ContainerEnvs
     */
    description?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum AppFile2ContainerEnvsConfigurableEnum {
    False = 'false',
    Basic = 'basic',
    Advanced = 'advanced'
}

