/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Original developer of this App
 * @export
 * @interface AppFile2Developer
 */
export interface AppFile2Developer {
    /**
     * Name of the developer
     * @type {string}
     * @memberof AppFile2Developer
     */
    name?: string;
    /**
     * Website of the developer
     * @type {string}
     * @memberof AppFile2Developer
     */
    website?: string;
    /**
     * Text to show in the donate button
     * @type {string}
     * @memberof AppFile2Developer
     */
    donate_text?: string;
    /**
     * Url to redirect when the donate button is clicked
     * @type {string}
     * @memberof AppFile2Developer
     */
    donate_url?: string;
}
