/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AppFile2ContainerLabels
 */
export interface AppFile2ContainerLabels {
    /**
     * Name of the label
     * @type {string}
     * @memberof AppFile2ContainerLabels
     */
    key?: string;
    /**
     * Value of the label
     * @type {string}
     * @memberof AppFile2ContainerLabels
     */
    value?: string;
}
