/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS AppFile
 * <p>   Currently the main role of OpenAPI is to define CasaOS App File schemas. </p>
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Changelog of the app
 * @export
 * @interface AppFile2Changelog
 */
export interface AppFile2Changelog {
    /**
     * Latest updates of the app
     * @type {string}
     * @memberof AppFile2Changelog
     */
    latestUpdates?: string;
    /**
     * URL of the changelog
     * @type {string}
     * @memberof AppFile2Changelog
     */
    url?: string;
}
